export const AUTH_API_URL = process.env.VUE_APP_AUTH_API_URL;
export const JIRA_API_URL = process.env.VUE_APP_JIRA_API_URL;
export const ATLASSIAN_API_URL = process.env.VUE_APP_ATLASSIAN_API_URL;
export const ATLASSIAN_AUTH_URL = process.env.VUE_APP_ATLASSIAN_AUTH_URL;
export const ATLASSIAN_AUDIENCE = process.env.VUE_APP_ATLASSIAN_AUDIENCE;
export const ATLASSIAN_CLIENT_ID = process.env.VUE_APP_ATLASSIAN_CLIENT_ID;
export const ATLASSIAN_SCOPE = process.env.VUE_APP_ATLASSIAN_SCOPE;
export const ATLASSIAN_REDIRECT_URI = process.env.VUE_APP_ATLASSIAN_REDIRECT_URI;
